spring:
  application:
    name: SECOND-SERVER
server:
  port: 8763
eureka:
  instance:
    instance-id: SECOND-SERVER
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8762/eureka,http://peer3:8764/eureka