spring:
  application:
    name: THIRD-SERVER
server:
  port: 8764
eureka:
  instance:
    instance-id: THIRD-SERVER
    hostname: peer3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8762/eureka,http://peer2:8763/eureka